spring:
  application:
    name: config-server    #向注册中心进行注册的服务名
  profiles:
    active: native #设置为本地启动的方式，而不是通过git
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/config